import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { QueryProvider } from "@/providers/query-provider";
import { ProtectedRoute } from "@/components/auth/protected-route";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< Updated upstream
      <body className="min-h-full flex flex-col">{children}</body>
=======
      <body className="min-h-full flex flex-col noise-overlay bg-neutral-50 text-neutral-900 selection:bg-[#eb0028] selection:text-white">
        <QueryProvider>
          <ProtectedRoute>
            {children}
          </ProtectedRoute>
        </QueryProvider>
      </body>
>>>>>>> Stashed changes
    </html>
  );
}
